apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: platform-catalogservice-secrets
  namespace: {{ .Values.namespace }}
spec:
  encryptedData:
{{ toYaml .Values.secrets | trim | indent 4 }}
  template:
    metadata:
      name: platform-catalogservice-secrets
      namespace: {{ .Values.namespace }}
    type: Opaque
status: {}
