apiVersion: v1
kind: Service
metadata:
  name: {{ include "platform-recommendationsservice.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "platform-recommendationsservice.name" . }}
    helm.sh/chart: {{ include "platform-recommendationsservice.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "platform-recommendationsservice.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
{{ toYaml .Values.service.ports | indent 4 }}
